services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: Dockerfile
    branch: main
    plan: free
    regions: oregon
    autoDeploy: true
    port: 5678
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://<seu-app>.onrender.com
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: N8N_BASIC_AUTH_USER
        value: seu_usuario
      - key: N8N_BASIC_AUTH_PASSWORD
        value: sua_senha
